name: Docker Image CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag leonardosartorello/seguranca_docker:${{ github.run_number }}
    - name: Docker Scout
  # You may pin to the exact commit or the version.
  # uses: docker/scout-action@d341d36d6eebbe05c0b25760c63afa19e8f23269
      uses: docker/scout-action@v1.17.0
      with:
        command: quickview
        image: leonardosartorello/seguranca_docker:${{ github.run_number }}
        # Ignore vulnerabilities from base image
        ignore-base: false # optional
        dockerhub-user: leonardosartorello # optional
        dockerhub-password: ${{ secrets.DOCKERHUB_PASS }}
    - name: Aqua Security Trivy
  # You may pin to the exact commit or the version.
  # uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5
      uses: aquasecurity/trivy-action@0.30.0
      with:
    # Scan type to use for scanning vulnerability
        image-ref: leonardosartorello/seguranca_docker:${{ github.run_number }}
        exit-code: 1 # optional
        severity: HIGH,CRITICAL
        format: table # optional, default is table
          
          
