name: Docker Image CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag leonardosartorello/seguranca_docker:${{ GITHUB_RUN_NUMBER }}
    - name: Docker Scout
  # You may pin to the exact commit or the version.
  # uses: docker/scout-action@d341d36d6eebbe05c0b25760c63afa19e8f23269
      uses: docker/scout-action@v1.17.0
      with: 
    
        command: quickview
        image: leonardosartorello/seguranca_docker:${{ GITHUB_RUN_NUMBER }}
        # Ignore vulnerabilities from base image
        ignore-base: false # optional
        # Comma separated list of severities (critical, high, medium, low, unspecified) to filter CVEs by
        only-severities: critical,high # optional
        # Fail the action step if vulnerability changes are detected
        exit-code: 1 # optional
        # Docker Hub User
        #dockerhub-user: # optional
        # Docker Hub PAT
        #dockerhub-password: # optional
          
